In [17]:
from sklearn.datasets import load_iris 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import confusion_matrix
import numpy as np 
from sklearn.model_selection import train_test_split 
iris_dataset=load_iris() 
X_train, X_test, y_train, y_test = train_test_split(iris_dataset["data"], iris_dataset["target"], random_state=0) 
kn = KNeighborsClassifier() 
kn.fit(X_train, y_train)
prediction1 = kn.predict(X_train)
prediction2 = kn.predict(X_test)
print(iris_dataset["data"][:5])
print(iris_dataset["target"][:5])
print(prediction)
print("Training Accuracy:"+ str(kn.score(X_train, y_train)))
print("Testing Accuracy:"+ str(kn.score(X_test, y_test)))
print("Training Confusion Matrix is : \n", confusion_matrix(y_train, prediction1))
print("Testing Confusion Matrix is : \n", confusion_matrix(y_test, prediction2))
target_names = iris_dataset.target_names
for pred,actual in zip(prediction,y_test):
    print("Prediction is "+str(target_names[pred])+", Actual is "+str(target_names[actual]))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
Training Accuracy:0.9732142857142857
Testing Accuracy:0.9736842105263158
Training Confusion Matrix is : 
 [[37  0  0]
 [ 0 32  2]
 [ 0  1 40]]
Testing Confusion Matrix is : 
 [[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
Prediction is virginica, Actual is virginica
Prediction is versicolor, Actual is versicolor
Prediction is setosa, Actual is setosa
Prediction is virginica, Actual is virginica
Prediction is setosa, Actual is setosa
Prediction is virginica, Actual is virginica
Prediction is setosa, Actual is setosa
Prediction is versicolor, Actual is versicolor
Prediction is versicolor, Actual is versicolor
Prediction is versicolor, Actual is versicolor
Prediction is virginica, Actual is virginica
Prediction is versicolor, Actual is versicolor
Prediction is versicolor, Actual is versicolor
Prediction is versicol